In [2]:
import pandas as pd

In [7]:
df = pd.read_csv('data/data.tsv', delimiter='\t', header=None)
df

                                                      0      1          2
0                         مرغ قرمه‌سبزی واسه هفته اشپزی  train  lifestyle
1     اغاز ثبت ‌نام کنکور دکتری سال اذر ثبت‌نام ازمو...  train  education
2     میدانید طبق ماده قانون هدفمندی یارانه‌ها مصوب ...  train  economics
3     درنگی کتاب کتابخوانی کتابخانه‌های عمومی کشور ک...  train        art
4     شرایطی تهران نظر کرونا قرمز جشنواره_فیلم_فجر ج...  train     health
...                                                 ...    ...        ...
1531  نگاهم دیپلماسی اقتصادی ظرفیت نقش سفیر تجارت دو...   test  economics
1532  فرامین خامنه‌ای هموطن قربانی امار رسمی انتشار ...   test     health
1533             تعویض رضا اسدی تاثیرگذار !!!! پرسپولیس   test      sport
1534  درروزی امتیاز نون شب واجب تره موقعیت سوزی‌های ...   test      sport
1535  خدا مشکل حلشم بجای ناراحتی غم ناامیدی بری سراغ...   test   religion

[1536 rows x 3 columns]

In [8]:
df.columns = ['text','split','label']

In [9]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Define the proportion for each set (e.g., 60% train, 20% test, 20% dev)
train_size = 0.6
test_size = 0.2
dev_size = 0.2

# Split the data
train, temp = train_test_split(df, test_size=1 - train_size, random_state=42)
test, dev = train_test_split(temp, test_size=test_size / (test_size + dev_size), random_state=42)

# Print the sizes of the resulting sets
print("Train set size:", len(train))
print("Test set size:", len(test))
print("Dev set size:", len(dev))

Train set size: 921
Test set size: 307
Dev set size: 308

In [11]:
train['split'] = 'train'
test['split'] = 'test'
dev['split'] = 'dev'

In [16]:
concatenated_df = pd.concat([train, test, dev], axis=0)


concatenated_df.reset_index(drop=True, inplace=True)

In [20]:
concatenated_df.to_csv('dataframe.tsv', sep='\t', index=False, encoding='utf-8')

In [21]:
df = pd.read_csv('dataframe.tsv', delimiter='\t')

In [22]:
df

                                                   text  split      label
0     مسایل اختلافی استحبابی امر بالمعروف لازم احکام...  train   religion
1     هموطنان عزیز تمنا مسافرت هواپیما کشتی قطار خور...  train  transport
2     معروف‌ترین غذاهای استانبول خوشمزه غذاهای ترکیه...  train  lifestyle
3     ترند نزولی بیتکوین واضح شکسته میتونه فیک بریک ...  train       tech
4     سلام امام مهربانم سلام نماینده خدا زمین سلام و...  train   religion
...                                                 ...    ...        ...
1531  ساعتی واحد اتریوم سرمایه_گذار کلان نهنگ صرافی ...    dev  economics
1532  استخدام مهندس فراوری دارای سابقه کار کارخانه ک...    dev  economics
1533  یا‌ طلعه الرشید خوب‌ ‌که ‌رخ ‌از اینه ‌پنهان ‌...    dev   religion
1534                  شاخص ترس طمع بیت‌کوین ترس بیتکوین    dev       tech
1535  اتنا دایمی زندان لاکان رشت بازداشت عفو الملل ا...    dev     social

[1536 rows x 3 columns]

In [25]:
train = df[df['split']=='train']
test = df[df['split']=='test']
dev = df[df['split']=='dev']
train

                                                  text  split      label
0    مسایل اختلافی استحبابی امر بالمعروف لازم احکام...  train   religion
1    هموطنان عزیز تمنا مسافرت هواپیما کشتی قطار خور...  train  transport
2    معروف‌ترین غذاهای استانبول خوشمزه غذاهای ترکیه...  train  lifestyle
3    ترند نزولی بیتکوین واضح شکسته میتونه فیک بریک ...  train       tech
4    سلام امام مهربانم سلام نماینده خدا زمین سلام و...  train   religion
..                                                 ...    ...        ...
916  باغ شیشه استند گل چوب شیشه چوب نراد روسی گل رش...  train  lifestyle
917  سفره ومیز مهمانی_خدا عرض طول عالم منوی مهمانی ...  train   religion
918  فریادهای یاحسین ابالفضل مردمی یاری رسانی سیل ب...  train    ecology
919  دانلود سریال قسمت فصل سریال سریال مجموعه تلویز...  train        art
920    تپسی گرم ستاره راننده زنگ زد دقیقه مشکلتون تپسی  train  transport

[921 rows x 3 columns]

In [ ]:
try:
    # Check if the specified text column exists in the DataFrame
    if text_column_name not in data_frame.columns:
        raise ValueError(f"'{text_column_name}' column not found in the DataFrame.")
        
    text_column = data_frame[text_column_name]
    
    vocab_set = set()

    for text in text_column:
        if pd.notna(text):  # Check for non-null values
            words = text.split()
            vocab_set.update(words)

    vocab_list = sorted(list(vocab_set))

    with open(output_file_path, 'w', encoding='utf-8') as vocab_file:
        for word in vocab_list:
            vocab_file.write(word + '\n')

    print(f'Vocabulary saved to {output_file_path}')

except Exception as e:
    print(f"An error occurred: {str(e)}")